import Home from "./home/Home";
//import SliderCard from "./home/SliderCard";
import JuniorWing from "./juniorwing/JuniorWing";
import Events from "./events/OurEvents";
import ContactUs from "./contactus/ContactUs";
import About from "./aboutus/About";
import Career from "./career/Career";
import Profile from "./myprofile/Profile";
import AwardRecognition from "./awardrecognition/AwardRecognition";
import Executive from "./newexecutive/Executive";
import Invoices from './invoice/Invoices';
import ConferenceandCertificates from "./conference/ConferenceandCertificates";
import Library from "./library/Library";
import Sidebar from "../components/layouts/Sidebar";
import AssociativeMembership from "./associative/AssociativeMembership";
export {Home, JuniorWing,Events,ContactUs,About,Career,Profile,AwardRecognition, Executive,Invoices,ConferenceandCertificates,Library,Sidebar,AssociativeMembership };